- cloudbuild.yaml
- latest.yml
Cloudbuild wasn't reading from the correct file, PR to fix.
> Fix cloudbuild

- latest.yml
| lrctl                   | 0.1.1             | 0.1.4             |
| open-collector | 0.1.1             | 0.1.3             |
> May 14th Version Update

- latest.yml
| lrctl                   | 0.1.1             | 0.1.6             |
| open-collector | 0.1.1             | 0.1.6             |
> Update versions for May 22nd release

- latest.yml
| lrctl                   | 0.1.6             | 0.1.7             |
| open-collector | 0.1.6             | 0.1.7             |
| eventhubbeat | 0.1.0             | 0.1.1             |
| gsbeat | n/a             | 0.1.1             |
> Update versions for June 12th release

- latest.yml
| lrctl                  | 0.1.7             | 0.1.8             |
> Update versions for June 13th release

- latest.yml
| lrctl                   | 0.1.8             | 0.1.9             |
| open-collector | 0.1.7             | 0.1.8             |
> Update versions for June 19th release

- latest.yml
| lrctl                   | 0.1.9             | 0.1.10           |
| open-collector | 0.1.8             | 0.1.10           |
> Update versions for July 11th release

- latest.yml
| lrctl                  | 0.1.10            | 1.1.11             |
| open-collector | 0.1.10             | 0.1.11           |
> Update versions for July 19th release

- latest.yml
| lrctl                  | 0.1.11            | 1.1.12             |
| open-collector | 0.1.11             | 0.1.12           |
> Update versions for August 5th release

- latest.yml
| lrctl                  | 0.1.16           | 1.1.17            |
| open-collector | 0.1.16          | 0.1.17           |
| pubsubbeat     | -                  | 1.2.0             |
> Update versions for October 22nd release

- latest.yml
| lrctl                  | 0.1.17           | 1.1.18            |
> Update versions for October 23rd

- latest.yml
| ehb.                 | 0.1.4           | 0.1.5            |
> Update versions for October 30th

- latest.yml
| lrctl                  | 0.1.23           | 1.1.24           |
| open-collector | 0.1.18          | 0.1.19           |
| metrics            | 0.2.0            | 0.3.0             |
> Update versions for November 20th release

- latest.yml
| lrctl                  | 0.1.27           | 1.1.27           |
| open-collector | 0.1.19          | 0.1.20           |
> Update versions for December 12th release

- latest.yml
Bumping up to the latest release
> open_collector version 0.1.21

- latest.yml
Update to lrctl container version 0.1.28
> update to lrctl version

- latest.yml
Updating version for LRCTL and Event hub beat.
> Versionhotfix

- latest.yml
- lrctl
> Release2021.08

- latest.yml
- lrctl
Verison Update for lrctl opencollector msgraphbeat
> Release2022.08

- latest.yml
This PR has updated version for CarbonBlackCloudBeat and PrismaCloudBeat.
> AugustOCReleaseTags

- latest.yml
> ENG-61623 defect fix

- latest.yml
This PR contains changes for MSGraph image latest version.
> Release2024.12

- latest.yml
- lrctl
Change GCR repository to JFROG repository and release image tag
> Release2025.04

- latest.yml
- lrctl
This PR has changes for OCT2025 GTM.
It has updated version of lrctl, metrics and o365beat.
> Release2025.10
